 module.exports = [
"The Bard's Tale Tavern",
"The Bard's Trousers",
"The Black Barnacle",
"The Black Flagon",
"The Bloody Body",
"The Bloody Tooth and Broken Bone Tavern",
"The Bottomless Cauldron",
"The Braze'n'Bold",
"The Bucket of Blood",
"The Busted Bottle",
"The Busty Barmaid",
"The Butterhouse Tavern",
"The Cellar-Keg",
"The Clay Platters",
"The Coal Miners Daughter",
"The Cob Web",
"The Cockatryce Egg",
"The Come on Inn",
"The Cracked Hoof",
"The Crooked Cane",
"The Dancing Dryad",
"The Dead Prince Tavern",
"The Dirty Sack Flophouse",
"River Stone",
"The Dock Master's Tavern",
"The Dragon's Slither",
"Dragonwink's Pub",
"The Drunken Dragon",
"The Drunken Sailor",
"The Drunk Duck",
"The Dwarven Bombard",
"Early Bird Inn",
"Every Man's Wish Tavern",
"The Fearless Flumph",
"The Fireside Newt",
"The Firewater Tavern",
"The First and Last Tavern",
"The Flaming Wand",
"The Flask and Sword",
"The Flying Flute Tavern",
"The Footsore Wanderer",
"The Fresh Flask",
"The Fried Fingers Inn",
"The Galleon-Hole",
"The Gory Club Tavern",
"The Gypsy's Gaze",
"The Hag's Pot Inn",
"The Happy Pedlar",
"The Harpey's Kettle",
"The Hearth and Road Inn",
"Hearty Wines and Aged Soups Inn",
"The Hare's Hair",
"House of Pots",
"The Inn and Out Inn",
"Inn Harm's Way",
"Inn way to Deep",
"Insatiable Badger",
"The Jasper Otter",
"The King's Hall",
"The Last Forgotten Wish Tavern",
"The Last Stop",
"The Magician's Monocle",
"The Mead and Magic Inn",
"The Merchant's Last Coin",
"The Minstrel's Dance",
"The Mixwater Tavern",
"The Moldy Eye",
"The Naughty Gnome",
"The Naughty Nymph",
"The Nymph's Node",
"The Ogre-Door Tabernacle",
"The Once-Proud Goose",
"The Open Cauldron",
"Oztrmo's Den",
"The Patched Paw",
"The Patched Robe",
"The Peasant's Flask",
"The Pewter Mug",
"The Phoenix's Beak",
"The Pocked Pocket Inn",
"The Poisoned Meat",
"The Poor Merchant's Inn",
"The Port Crevice",
"The Queen's Robes",
"The Rather Blustery Day",
"The Rat's Daggers",
"The Red Homununch",
"The Reveling Wench",
"The Rich Peasant Inn and Tavern",
"The Riverman's Nestledown",
"The Rock Bunk Tavern",
"The Rotten Bolas",
"The Running King",
"The Rusty Cog Inn",
"The Salt Merchant Inn",
"The Salty Tusk",
"Scorfil's Ale & Fryes",
"The Scrolls of Welcoming",
"The Servant's Last Dance",
"The Shaken Flagon",
"The Shattered Cup Hall",
"The Shield and Sheath Inn",
"The Shitkicker",
"The Silly Dryad",
"The Silver Sword Inn",
"Sleemy's Second Home",
"The Slurred Speech Tavern",
"The Spider's Fang",
"The Spider's Nest",
"The Steward's Hatch",
"The Stowaway Inn",
"The Swaggering Magus",
"The Swordhole",
"The Tall Tales Tavern",
"The Tanger Serpent Tavern",
"The Tangled Vine Tavern",
"The Tassled Teapot",
"The Tasty Timber",
"The Traveler's Notch",
"The Unfilled Mug",
"The Unkempt Virgin",
"The Vomit Repository",
"The Wanderlust Tavern",
"The Watering Hole",
"Wayfinder's Rest",
];